language: java
sudo:
  - false
dist:
  - trusty
addons:
  apt:
    packages:
      - oracle-java9-installer
jdk:
  - oraclejdk9
install:
  - mvn install -DskipTests=true -Dgpg.skip=true -B -V -U
after_success:
  - mvn jacoco:report coveralls:report